	'<?php echo $datos_usuario[$i]['sop'
	'<?php echo $datos_usuario[$i]['fecsol'
	'<?php echo $datos_usuario[$i]['nomusu'
	'<?php echo $datos_usuario[$i]['apusu'
	'<?php echo $datos_usuario[$i]['arealab'
	'<?php echo $datos_usuario[$i]['tserv'
	'<?php echo $datos_usuario[$i]['sclie'
	'<?php echo $datos_usuario[$i]['cinom'
	'<?php echo $datos_usuario[$i]['asinom'
	'<?php echo $datos_usuario[$i]['asiape'
	'<?php echo $datos_usuario[$i]['fecasi'
	'<?php echo $datos_usuario[$i]['uninom'
	'<?php echo $datos_usuario[$i]['tecnom'
	'<?php echo $datos_usuario[$i]['tecape'
	'<?php echo $datos_usuario[$i]['fecate'
	'<?php echo $datos_usuario[$i]['fanom'
	'<?php echo $datos_usuario[$i]['atendido'
	'<?php echo $datos_usuario[$i]['reprogramar'
	'<?php echo $datos_usuario[$i]['cotizar'
	'<?php echo $datos_usuario[$i]['obs1'
	'<?php echo $datos_usuario[$i]['obs2'
    '<?php echo $datos_usuario[$i]['obs3'] ?>'

sop,fecsol,nomusu,apusu,arealab,tserv,sclie,cinom,asinom,asiape,fecasi,uninom,tecnom,tecape,fecate,fanom,atendido,reprogramar,cotizar,obs1,obs2,obs3